### ISSUE TITLE
Issues in connecting with API

### ISSUE THREAD

**Issue by nidhis** [davereid/toggl-php-sdk#2]
Hi, 
We are using the code from below link:

https://github.com/davereid/toggl-php-sdk

We have successfully installed PEAR on our local server but please guide us about the following line:

require_once 'PHPUnit/Framework/TestCase.php';

We have placed this folder "PHPUnit" in our project and we are receiving the following error on the above line:

Fatal error: Class 'PHPUnit_Framework_Assert' not found.

Please let us know:
1. Why do we require PHPUnit?
2. Is the code at "https://github.com/davereid/toggl-php-sdk" sufficient to connect with Toggl API?

We have created a free account and have replaced the token in the file.

Please guide us.

Thanks in advance.

**Comment by davereid** [comment]
1. PHPUnit is only required to run the unit tests.
2. Yes, the src/toggl.php is the only file required to connect and interact with the Toggl API. Keep in mind you'll still have to write the code to perform the logic with what you want to do, but the actual interaction with the API is done for you.

**Comment by nidhis** [comment]
Hi,
We are working for retailmicro.com and facing some issues in integrating and following up with Toggl API.

When we try authenticate ourselves with the token, it returns nothing and creating cookies as we can see in browser cookies. It is not returning anything as shown on https://www.toggl.com/public/api
{
      "data": {
          "email": "johndoe@gmail.com",
          "date_format": "%m/%d/%Y",
          "new_time_entries_start_automatically": true,
          "language": "en_US",
          "api_token": "ffc3f3024ec5d40cee2e24d5ff023c12",
          "fullname": "John Doe",
          "time_entry_retention_days": 9,
          "jquery_date_format": "m/d/Y",
          "default_workspace_id": 31366,
          "jquery_timeofday_format": "H:i",
          "beginning_of_week": 1,
          "id": 42182,
          "timeofday_format": "%H:%M"
      },
      "related_data_updated_at": "2010-06-29T11:17:19+03:00"
}

Also, if after running the authentication code, we try to create client without sending any details, we were receiving error”Name cannot be blank”. But if we send name along with the request, we get blank response from the API without any confirmation and the client is not created.

Please let us know the issues or what else is required other than PEAR. 

One more question, why is PEAR installation required?

Kind Regards

Nidhi
Teckbiz
